setw -g xterm-keys on
set -s escape-time 10
set -sg repeat-time 600
set -g history-limit 5000
set -g base-index 1
setw -g pane-base-index 1
setw -g automatic-rename on
set -g renumber-windows on
set -g set-titles on
set -g display-panes-time 800
set -g display-time 1000
set -g status-interval 10
bind -n C-l send-keys C-l \; run 'sleep 0.2' \; clear-history
set -g monitor-activity on
set -g visual-activity off
tmux_conf_new_pane_retain_current_path=true
tmux_conf_24b_colour=true
tmux_conf_theme=enabled

#status bar
set -g status on
set -g status-position top
set -g status-bg colour235
set -g status-fg colour136
# формат для незакрытой вкладки
set-window-option -g window-status-format " #I #W "
# формат для активной вкладки
set-window-option -g window-status-current-format "#[fg=colour231]#[bg=colour240] #I #W #[default]"

# дополнительные поля слева/справа (имя сессии, время)
set -g status-left  "#[fg=green] #S "
set -g status-right "#[fg=colour246] %Y-%m-%d  %H:%M "

tmux_conf_theme_status_left=" ❐ #S
tmux_conf_theme_status_right=" #{prefix} #{?battery_percentage,…} , %d %b %R "

#symbols
tmux_conf_theme_pairing="⚇"
tmux_conf_theme_prefix="⌨"
tmux_conf_theme_mouse="↗"
tmux_conf_theme_root="!"
tmux_conf_theme_synchronized="⚏

# battary
tmux_conf_battery_bar_symbol_full="◼"
tmux_conf_battery_bar_symbol_empty="◻"
tmux_conf_battery_bar_length="auto"
tmux_conf_battery_bar_palette="gradient"

#plugins
tmux_conf_update_plugins_on_launch=true
tmux_conf_update_plugins_on_reload=true
tmux_conf_uninstall_plugins_on_reload=true

set -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
